DIR: 
  exp: "trainOn400"
  snapshot: "/home/bswang/private/RL_results/stnp"

SIMULATOR:
  population: 100000
  num_days: 101
  num_simulations: 30
  init_infected: 2000
  init_exposed: 2000
  

MODEL:
  backbone: "deepQ"

TRAIN:
  episode: 300
  resume: "checkpoint_000000"
  stnp_epoch: 2000
  train_iter: 8
  epoch_iters: 500
  n_display: 500
  patience: 5000
  device: "cuda:0"
  
  max_actions: 25
  update_every_n_steps: 100
  learning_iterations: 150
  reward_penalty: 1.0
  

VAL:
  resume: "checkpoint_000000"
  evaluate_only: False
  visualization: False